(() => {
  'use strict';
  const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
  const setup=document.querySelector('#setup'),countSelect=document.querySelector('#pieceCount'),autoSize=document.querySelector('#autoSize');
  const skinsBlue=document.querySelector('#skinsBlue'),skinsRed=document.querySelector('#skinsRed'),skinError=document.querySelector('#skinError');
  const turnLabel=document.querySelector('#turnLabel'),turnSub=document.querySelector('#turnSub'),turnDot=document.querySelector('#turnDot'),blueScore=document.querySelector('#blueScore'),redScore=document.querySelector('#redScore'),status=document.querySelector('#status'),win=document.querySelector('#win'),winTitle=document.querySelector('#winTitle'),winText=document.querySelector('#winText');
  const TAU=Math.PI*2,R=21,skinColors=['#2671ff','#ed5b64','#20a878','#f39a3d','#8d5de8','#f05ca6','#18a8b8','#e5c04b','#425466','#ef7138','#6e9b4a','#9b5a42','#7857a8','#36a6e0','#ce3e74','#75b847','#f06f55','#5568d8','#c39239','#3c9290','#a149a5','#e25e86','#62a6a0','#c76c2c','#5b74a3','#b24c3f','#4b9e61','#9274b8','#d49b36','#3b6c99'],skinEmojis=['🐰','🐱','🐶','🐼','🐸','🐥','🦊','🐻','🐷','🐨','🐯','🐵','🐹','🐙','🦄','🐳','🐧','🍓','🍋','🍉','🍪','🍩','🍭','⭐','🌈','🌸','💜','🧁','🍀','🎀'];
  let dpr=1,W=0,pieces=[],current='blue',aim=null,moving=false,gameOver=false,last=0,audio,arena=3,skin={blue:0,red:1},pieceCount=5;
  const pockets=[[.06,.06],[.94,.06],[.06,.94],[.94,.94]],clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  for(let i=1;i<=30;i++){const o=document.createElement('option');o.value=i;o.textContent=i+'개';if(i===5)o.selected=true;countSelect.appendChild(o);}
  function createSkins(host,team){skinColors.forEach((color,i)=>{const b=document.createElement('button');b.className='skin'+(i===skin[team]?' selected':'');b.style.setProperty('--skin',color);b.textContent=skinEmojis[i];b.title='스킨 '+(i+1)+' '+skinEmojis[i];b.setAttribute('aria-label','스킨 '+(i+1)+' '+skinEmojis[i]);b.dataset.index=i;b.onclick=()=>{skin[team]=i;host.querySelectorAll('.skin').forEach(x=>x.classList.toggle('selected',Number(x.dataset.index)===i));skinError.hidden=skin.blue!==skin.red;};host.appendChild(b);});}
  createSkins(skinsBlue,'blue');createSkins(skinsRed,'red');
  function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;canvas.width=W*dpr;canvas.height=W*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);}
  function piece(team,x,y){return{team,x,y,vx:0,vy:0,active:true,skin:skin[team]};}
  function reset(){pieces=[];const n=pieceCount,cols=Math.ceil(Math.sqrt(n)),gap=Math.min(.12,.58/(cols||1));for(let i=0;i<n;i++){const col=i%cols,row=Math.floor(i/cols),x=.5+(col-(cols-1)/2)*gap,y=.39+row*gap;pieces.push(piece('blue',x*W,y*W));pieces.push(piece('red',x*W,(.61-row*gap)*W));}current='blue';aim=null;moving=false;gameOver=false;win.hidden=true;updateUI();status.textContent='파란 알을 골라서 첫 공격을 시작하세요.';}
  function arenaForCount(n){return n<=6?1:n<=12?2:n<=18?3:n<=24?4:5;}
  function updateAutoSize(){arena=arenaForCount(Number(countSelect.value));autoSize.textContent='알 개수에 따라 자동 · '+arena+'단계 '+(arena===1?'좁게':arena===5?'넓게':'');}
  function openSetup(){setup.hidden=false;countSelect.value='5';skin.blue=0;skin.red=1;skinsBlue.querySelectorAll('.skin').forEach((x,i)=>x.classList.toggle('selected',i===0));skinsRed.querySelectorAll('.skin').forEach((x,i)=>x.classList.toggle('selected',i===1));skinError.hidden=true;updateAutoSize();}
  function updateUI(){blueScore.textContent=pieces.filter(p=>p.active&&p.team==='blue').length;redScore.textContent=pieces.filter(p=>p.active&&p.team==='red').length;turnLabel.textContent=current==='blue'?'파랑의 차례':'빨강의 차례';turnSub.textContent=moving?'알이 멈출 때까지 기다리세요':'알을 골라 힘을 모아보세요';turnDot.className='turn-dot '+(current==='red'?'red':'');}
  function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top};}
  function start(e){if(moving||gameOver)return;const q=point(e),p=pieces.find(v=>v.active&&v.team===current&&Math.hypot(v.x-q.x,v.y-q.y)<R*1.7);if(!p)return;aim={p,x:q.x,y:q.y};canvas.setPointerCapture?.(e.pointerId);status.textContent='반대 방향으로 당겨서 세기를 조절하세요.';}
  function move(e){if(aim){const q=point(e);aim.x=q.x;aim.y=q.y;}}
  function release(){if(!aim)return;const p=aim.p,dx=p.x-aim.x,dy=p.y-aim.y,len=Math.hypot(dx,dy);aim=null;if(len<7){status.textContent='조금 더 길게 당겨보세요.';return;}const power=Math.min(len,180);p.vx=dx/len*power*.12;p.vy=dy/len*power*.12;moving=true;beep(170,.06);status.textContent='휙! 선 밖으로 나가면 아웃입니다.';}
  function beep(freq,duration){try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch(_){} }
  function pocket(p){return pockets.some(([x,y])=>Math.hypot(p.x-x*W,p.y-y*W)<35);}
  function outOfBounds(p){const inset=(.055+(5-arena)*.032)*W;return p.x<inset||p.x>W-inset||p.y<inset||p.y>W-inset;}
  function tick(dt){if(!moving)return;const active=pieces.filter(p=>p.active),edge=R;active.forEach(p=>{p.x+=p.vx*dt*60;p.y+=p.vy*dt*60;p.vx*=Math.pow(.984,dt*60);p.vy*=Math.pow(.984,dt*60);if(pocket(p)){p.active=false;p.vx=p.vy=0;beep(90,.1);status.textContent='구멍에 들어가서 아웃!';return;}if(p.x<edge||p.x>W-edge){p.x=clamp(p.x,edge,W-edge);p.vx*=-.78;beep(220,.025);}if(p.y<edge||p.y>W-edge){p.y=clamp(p.y,edge,W-edge);p.vy*=-.78;beep(220,.025);}});for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const a=active[i],b=active[j];if(!a.active||!b.active)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=R*2;if(d&&d<min){const nx=dx/d,ny=dy/d,over=(min-d)/2;a.x-=nx*over;a.y-=ny*over;b.x+=nx*over;b.y+=ny*over;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){a.vx+=rel*nx;a.vy+=rel*ny;b.vx-=rel*nx;b.vy-=rel*ny;beep(310,.03);}}}if(active.every(p=>Math.abs(p.vx)+Math.abs(p.vy)<.035)){active.forEach(p=>p.vx=p.vy=0);moving=false;const other=current==='blue'?'red':'blue';if(!pieces.some(p=>p.active&&p.team===other)){gameOver=true;winTitle.textContent=(current==='blue'?'파랑':'빨강')+' 승리!';winText.textContent='상대 알을 모두 밀어냈어요. 멋진 한 수였습니다!';win.hidden=false;status.textContent='게임 종료 · 다시 시작해서 한 판 더!';}else{current=other;status.textContent=(current==='blue'?'파랑':'빨강')+' 차례입니다. 내 알을 선택하세요.';updateUI();}}}
  function drawSkin(p,c){const i=p.skin,eye='#24343a';const dot=(x,y,r,col)=>{ctx.fillStyle=col;ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fill();};const tri=(a,b,d,col)=>{ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.lineTo(...d);ctx.closePath();ctx.fill();};ctx.lineWidth=2;
    if(i===0){tri([-15,-12],[-9,-29],[-2,-13],'#fff0f1');tri([2,-13],[9,-29],[15,-12],'#fff0f1');dot(-7,-3,4,'#fff');dot(7,-3,4,'#fff');dot(-7,-3,2,eye);dot(7,-3,2,eye);dot(0,7,4,'#ffb0ba');}
    else if(i===1){tri([-15,-9],[-13,-28],[-1,-16],'#ffe5ef');tri([1,-16],[13,-28],[15,-9],'#ffe5ef');dot(-7,-3,3,'#fff');dot(7,-3,3,'#fff');dot(-7,-3,2,eye);dot(7,-3,2,eye);ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(-4,5);ctx.lineTo(-16,2);ctx.moveTo(4,5);ctx.lineTo(16,2);ctx.stroke();}
    else if(i===2){dot(-13,-13,9,'#fff');dot(13,-13,9,'#fff');dot(-7,-3,4,'#fff');dot(7,-3,4,'#fff');dot(-7,-3,2,eye);dot(7,-3,2,eye);dot(0,8,4,'#77463d');}
    else if(i===3){dot(-7,-4,6,'#26343a');dot(7,-4,6,'#26343a');dot(-7,-4,2,'#fff');dot(7,-4,2,'#fff');dot(0,7,5,'#fff');}
    else if(i===4){dot(-9,-20,7,'#8be4a4');dot(9,-20,7,'#8be4a4');dot(-9,-20,3,'#fff');dot(9,-20,3,'#fff');dot(-9,-20,1.5,eye);dot(9,-20,1.5,eye);ctx.strokeStyle='#24343a';ctx.beginPath();ctx.arc(0,6,8,.15*Math.PI,.85*Math.PI);ctx.stroke();}
    else if(i===5){dot(-7,-4,3,'#fff');dot(7,-4,3,'#fff');dot(-7,-4,1.5,eye);dot(7,-4,1.5,eye);tri([-5,6],[0,12],[5,6],'#f2a936');}
    else if(i===6||i===10||i===14){tri([-15,-9],[-10,-29],[-1,-13],i===14?'#fff4ae':'#f7b26a');tri([1,-13],[10,-29],[15,-9],i===14?'#fff4ae':'#f7b26a');dot(-7,-3,3,'#fff');dot(7,-3,3,'#fff');dot(-7,-3,1.5,eye);dot(7,-3,1.5,eye);if(i===10){ctx.strokeStyle='#8b3f2b';ctx.beginPath();ctx.moveTo(-14,8);ctx.lineTo(-6,3);ctx.moveTo(6,3);ctx.lineTo(14,8);ctx.stroke();}if(i===14){tri([-4,-25],[0,-35],[4,-25],'#ffe478');}}
    else if(i===7||i===9||i===11){dot(-14,-15,9,'#b88b70');dot(14,-15,9,'#b88b70');dot(-7,-3,4,'#fff');dot(7,-3,4,'#fff');dot(-7,-3,2,eye);dot(7,-3,2,eye);dot(0,7,4,'#5c3c34');}
    else if(i===8){dot(-7,-3,4,'#fff');dot(7,-3,4,'#fff');dot(-7,-3,2,eye);dot(7,-3,2,eye);dot(-5,8,3,'#ffb0b8');dot(5,8,3,'#ffb0b8');}
    else if(i===12){dot(-7,-3,3,'#fff');dot(7,-3,3,'#fff');dot(-7,-3,2,eye);dot(7,-3,2,eye);dot(-13,7,5,'#ffd2d7');dot(13,7,5,'#ffd2d7');}
    else if(i===13||i===15||i===16){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,2,12,0,TAU);ctx.stroke();dot(-7,-4,3,'#fff');dot(7,-4,3,'#fff');dot(-7,-4,1.5,eye);dot(7,-4,1.5,eye);if(i===15){tri([-20,2],[-29,-5],[-22,10],'#c9f6ff');tri([20,2],[29,-5],[22,10],'#c9f6ff');}}
    else{ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=4;ctx.beginPath();if(i%3===0){ctx.moveTo(-16,-9);ctx.lineTo(16,9);ctx.moveTo(-16,9);ctx.lineTo(16,-9);}else if(i%3===1){ctx.arc(0,0,12,0,TAU);}else{ctx.moveTo(-18,0);ctx.lineTo(18,0);ctx.moveTo(0,-18);ctx.lineTo(0,18);}ctx.stroke();dot(-7,-7,3,'#fff');dot(7,7,3,'#fff');}
    ctx.font='22px "Segoe UI Emoji","Apple Color Emoji",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(skinEmojis[i],0,1);
  }
  function draw(){ctx.clearRect(0,0,W,W);const g=ctx.createLinearGradient(0,0,W,W);g.addColorStop(0,'#b9d9b6');g.addColorStop(1,'#8fbea0');ctx.fillStyle=g;ctx.fillRect(0,0,W,W);pockets.forEach(([x,y])=>{ctx.beginPath();ctx.fillStyle='#263b3c';ctx.shadowColor='rgba(20,38,39,.3)';ctx.shadowBlur=7;ctx.arc(x*W,y*W,29,0,TAU);ctx.fill();ctx.shadowBlur=0;});pieces.filter(p=>p.active).forEach(p=>{ctx.save();ctx.translate(p.x,p.y);ctx.beginPath();ctx.fillStyle='rgba(32,52,47,.2)';ctx.ellipse(3,6,R*1.05,R*.82,0,0,TAU);ctx.fill();const c=skinColors[p.skin],grad=ctx.createRadialGradient(-R*.35,-R*.42,2,0,0,R);grad.addColorStop(0,'#fff');grad.addColorStop(.14,c);grad.addColorStop(1,c+'cc');ctx.beginPath();ctx.fillStyle=grad;ctx.arc(0,0,R,0,TAU);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=2;ctx.stroke();drawSkin(p,c);ctx.restore();});if(aim){const p=aim.p;ctx.save();ctx.setLineDash([7,7]);ctx.strokeStyle=skinColors[p.skin];ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+(p.x-aim.x)*.8,p.y+(p.y-aim.y)*.8);ctx.stroke();ctx.restore();}}
  function frame(t){const dt=Math.min((t-last)/1000,.035)||0;last=t;tick(dt);draw();requestAnimationFrame(frame);}
  function begin(){if(skin.blue===skin.red){skinError.hidden=false;return;}pieceCount=Number(countSelect.value);updateAutoSize();setup.hidden=true;resize();reset();}
  window.addEventListener('resize',resize);countSelect.addEventListener('change',updateAutoSize);canvas.addEventListener('pointerdown',start);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);document.querySelector('#play').onclick=begin;document.querySelector('#reset').onclick=openSetup;document.querySelector('#again').onclick=openSetup;updateAutoSize();resize();draw();requestAnimationFrame(frame);
})();
